(()=>{'use strict';
const {lessons,questions}=window.BEP_DATA, app=document.getElementById('app');
const categories={fundamentals:'Business Fundamentals',economics:'Economics',csr:'CSR & Greenwashing',international:'International Business'};
let saved;try{saved=JSON.parse(localStorage.getItem('bep-review-v1')||'{}')}catch{saved={}}
let state={wrong:[],mastered:[],history:[],...saved}, mode='',session=[],answers={},submitted=false,curveIndex=0;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem('bep-review-v1',JSON.stringify(state))}catch{}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function options(list){return list.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
function change(m){mode=m;session=[];answers={};submitted=false;document.querySelectorAll('[data-mode]').forEach(b=>{b.classList.toggle('active',b.dataset.mode===m);b.setAttribute('aria-pressed',b.dataset.mode===m)});if(m==='learn')learn();else if(m==='curve')curve();else setup();}
function learn(){app.innerHTML=`<p>Explain the concept aloud, then try a quick check. Start with the topic you find hardest.</p><p><a href="unit1.html">Review existing Business Fundamentals notes</a></p><p id="learn-progress" class="muted"></p>`+lessons.map((l,i)=>`<details class="topic"><summary>${esc(l[0])}</summary><p class="sources">Class source: ${esc(l[2])}</p>${l[3].map(([term,text])=>`<h3>${esc(term)}</h3><p>${esc(text)}</p>`).join('')}<label class="check"><input type="checkbox" data-master="${i}" ${state.mastered.includes(i)?'checked':''}> I can explain these ideas without notes</label><button data-topicquiz="${l[1]}">Practise ${esc(categories[l[1]])}</button></details>`).join('');updateLearn();app.querySelectorAll('[data-master]').forEach(el=>el.onchange=()=>{const i=+el.dataset.master;state.mastered=state.mastered.filter(n=>n!==i);if(el.checked)state.mastered.push(i);persist();updateLearn()});app.querySelectorAll('[data-topicquiz]').forEach(b=>b.onclick=()=>{change('practice');document.getElementById('category').value=b.dataset.topicquiz;start()})}
function updateLearn(){document.getElementById('learn-progress').textContent=`Self-check: ${state.mastered.length} / ${lessons.length} new lesson sections marked confident.`}
function setup(){let mistakes=mode==='mistakes';app.innerHTML=`<h2>${mode==='test'?'Cumulative mock test':mistakes?'Review missed questions':'Quick check'}</h2><p>${mode==='test'?'30 randomized questions: 10 fundamentals, 12 economics, 4 CSR and 4 international business. Aim for 30–40 minutes including the written practice. Answers appear after submission.':mistakes?'Redo questions you missed in quick checks, mock tests and curve challenges.':'Choose a topic for 10 questions with immediate explanations.'}</p><div class="setup">${!mistakes&&mode!=='test'?`<label class="field"><span>Topic</span><select id="category"><option value="all">All topics</option>${Object.entries(categories).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select></label>`:''}<button id="start" class="primary">${mistakes?'Retry missed questions':mode==='test'?'Start mock test':'Start quick check'}</button></div><p class="muted">Question bank: 93 questions. Missed items: ${state.wrong.length}.</p>${state.history.length?`<details><summary>Recent mock test results</summary>${state.history.slice(-5).reverse().map(h=>`<p>${esc(h.date)} · ${h.score}/${h.total}</p>`).join('')}</details>`:''}`;document.getElementById('start').onclick=start;}
function start(){answers={};submitted=false;if(mode==='test')session=shuffle(Object.keys(categories).flatMap(c=>shuffle(questions.filter(q=>q.category===c)).slice(0,{fundamentals:10,economics:12,csr:4,international:4}[c])));else if(mode==='mistakes'){session=shuffle(questions.filter(q=>state.wrong.includes(q.id))).slice(0,15);if(!session.length){app.innerHTML='<p>No missed questions yet. Try a quick check or mock test first.</p>';return}}else{let c=document.getElementById('category').value;session=shuffle(questions.filter(q=>c==='all'||q.category===c)).slice(0,10)}renderQuiz()}
function renderQuiz(){app.innerHTML=`<h2>${mode==='test'?'Mock test':mode==='mistakes'?'Mistake review':'Quick check'}</h2><p>${session.length} questions · ${mode==='test'?'Submit when finished. Unanswered questions score zero.':'Choose an answer, then check it.'}</p><p id="answered" class="muted" aria-live="polite"></p><form id="review-quiz">${session.map((q,i)=>`<section class="question" id="section-${q.id}"><p class="muted">${esc(categories[q.category])}</p><fieldset><legend>${i+1}. ${esc(q.question)}</legend>${q.options.map((o,j)=>`<label class="choice"><input type="radio" name="${q.id}" value="${j}"><span>${String.fromCharCode(65+j)}. ${esc(o)}</span></label>`).join('')}</fieldset>${mode!=='test'?`<button type="button" data-check="${q.id}">Check this answer</button>`:''}<p class="feedback" id="fb-${q.id}" hidden></p></section>`).join('')}<div class="tools"><button type="submit" class="primary">${mode==='test'?'Submit test':'Check all answers'}</button><button type="button" id="new">New set</button></div></form><section id="result" aria-live="polite"></section>${mode==='test'?written():''}`;app.querySelectorAll('input[type=radio]').forEach(el=>el.onchange=()=>{answers[el.name]=+el.value;document.getElementById('answered').textContent=`Answered: ${Object.keys(answers).length} / ${session.length}`});app.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{let q=session.find(q=>q.id===b.dataset.check);feedback(q)});document.getElementById('review-quiz').onsubmit=e=>{e.preventDefault();let score=0,stats={};session.forEach(q=>{const yes=feedback(q);score+=yes;stats[q.category]??={right:0,total:0};stats[q.category].total++;stats[q.category].right+=yes});document.getElementById('result').innerHTML=`<p class="result">${score}/${session.length} (${Math.round(score/session.length*100)}%)</p><div class="scroll"><table><tr><th>Topic</th><th>Result</th><th>Next step</th></tr>${Object.entries(stats).map(([c,s])=>`<tr><td>${esc(categories[c])}</td><td>${s.right}/${s.total}</td><td>${s.right===s.total?'Explain one answer aloud':'Review notes and retry missed questions'}</td></tr>`).join('')}</table></div>${mode==='test'?'<p>Written responses below are self-assessed and excluded from this score.</p>':''}`;if(mode==='test'&&!submitted){state.history.push({date:new Date().toLocaleString(),score,total:session.length});state.history=state.history.slice(-10);persist()}submitted=true;document.getElementById('result').scrollIntoView({behavior:'smooth',block:'start'})};document.getElementById('new').onclick=()=>change(mode);}
function remember(id,correct){state.wrong=state.wrong.filter(x=>x!==id);if(!correct)state.wrong.push(id);persist()}
function feedback(q){let selected=answers[q.id];if(selected===undefined&&mode!=='test'){let f=document.getElementById('fb-'+q.id);f.hidden=false;f.textContent='Choose an answer first.';return 0}let correct=selected===q.answer;remember(q.id,correct);let f=document.getElementById('fb-'+q.id);f.hidden=false;f.className='feedback '+(correct?'correct':'incorrect');f.textContent=(correct?'Correct. ':selected===undefined?'Unanswered. ':'Incorrect. ')+`Answer: ${q.options[q.answer]}. ${q.explanation}`;return +correct}
function written(){return `<h2>Written practice · self-assess</h2><p>Use concept → evidence from the scenario → consequence. These responses are not automatically marked.</p>`+[
['Consumers become health-conscious and buy fewer donuts. Explain the curve change and equilibrium effects.','Demand shifts left due to changing tastes (BITER); supply is unchanged. Equilibrium price and quantity fall. Include labelled price/quantity axes and the old and new demand curves.'],
['A clothing company finds unsafe conditions at an overseas supplier. A safer supplier costs more. Recommend a response using the triple bottom line.','People: protect workers and verify conditions. Planet: assess environmental practices. Profit: higher short-term costs may be balanced by trust and lower reputational risk. State a concrete action, such as independent auditing and a corrective plan or changing suppliers, and explain the trade-off.'],
['Canada exports $620B and imports $680B. Calculate the balance and explain one benefit and one cost of a tariff.','620 − 680 = −$60B: trade deficit. A tariff can protect local producers/jobs by increasing import costs, but consumers or importing businesses may pay more.'],
['Four airlines face high startup costs. Identify the market structure and give two pieces of evidence.','Oligopoly: few dominant sellers and high barriers to entry. Explain how one airline’s pricing can affect competitors.'],
['A brand advertises “40% less water used” but has no report or supporting data. Evaluate its claim and suggest better communication.','No proof is the clearest pattern. Ask for a baseline, measurement method, time period and verifiable results; disclose limitations and broader impacts. A specific claim needs evidence.']
].map(([q,a],i)=>`<section class="short"><h3>${i+1}. ${esc(q)}</h3><textarea aria-label="Written response ${i+1}" placeholder="Write your explanation before opening the model answer."></textarea><details class="answer"><summary>Model answer and self-check</summary><p>${esc(a)}</p></details></section>`).join('')}
const curves=[
{q:'Consumers become health-conscious and buy fewer donuts.',change:'Demand left',p:'Falls',qty:'Falls',id:'q62',why:'Tastes change (BITER). Demand falls at every price; supply stays unchanged.'},
{q:'Avocados become more popular; production conditions stay unchanged.',change:'Demand right',p:'Rises',qty:'Rises',why:'Tastes change (BITER). Demand rises at every price.'},
{q:'A disease reduces egg production; buyers’ preferences stay unchanged.',change:'Supply left',p:'Rises',qty:'Falls',id:'q63',why:'Production capacity falls; supply decreases at every price.'},
{q:'A subsidy lowers hoodie production costs; demand stays unchanged.',change:'Supply right',p:'Falls',qty:'Rises',id:'q56',why:'Subsidies (STERN) encourage production at every price.'},
{q:'Coke becomes more expensive. Analyse Pepsi, whose own price is unchanged.',change:'Demand right',p:'Rises',qty:'Rises',id:'q53',why:'Coke and Pepsi are substitutes. Pepsi demand rises; its supply is unchanged.'},
{q:'Gasoline becomes more expensive. Analyse SUVs; SUV supply stays unchanged.',change:'Demand left',p:'Falls',qty:'Falls',id:'q54',why:'Gasoline and SUVs are complements. SUV demand falls.'},
{q:'A T-shirt’s own price falls while all non-price determinants stay unchanged.',change:'Movement along demand',p:'Not a new equilibrium',qty:'Quantity demanded rises',id:'q50',why:'The given own-price change moves along the demand curve. It does not identify a new market equilibrium.'},
{q:'A cell phone’s own price rises while all non-price determinants stay unchanged.',change:'Movement along supply',p:'Not a new equilibrium',qty:'Quantity supplied rises',id:'q51',why:'Quantity supplied rises along the same supply curve; supply itself does not shift.'},
{q:'Fewer people want pianos, and piano stores close. Demand and supply both decrease.',change:'Both left',p:'Cannot determine',qty:'Falls',id:'q64',why:'Both shifts lower quantity. Demand left lowers price, but supply left raises it; their relative sizes determine the result.'},
{q:'New buyers enter the laptop market and production technology improves. Demand and supply both increase.',change:'Both right',p:'Cannot determine',qty:'Rises',id:'q66',why:'Both shifts raise quantity. Price may rise, fall or remain unchanged, depending on relative shifts.'},
{q:'DVDs become less popular and a production tax raises sellers’ costs.',change:'Both left',p:'Cannot determine',qty:'Falls',id:'q65',why:'Demand and supply both fall. Quantity falls; price is ambiguous.'}
];
function graph(c,reveal){let dl=c.change.includes('Demand left')||c.change==='Both left'?-55:c.change.includes('Demand right')||c.change==='Both right'?55:0,sl=c.change.includes('Supply left')||c.change==='Both left'?-55:c.change.includes('Supply right')||c.change==='Both right'?55:0;let moveD=c.change==='Movement along demand',moveS=c.change==='Movement along supply';return `<svg class="graph" viewBox="0 0 460 360" role="img" aria-label="${esc(reveal?'Original demand and supply plus the answer’s change':'Original demand and supply curves; price on vertical axis, quantity on horizontal axis')}"><path d="M55 25V305H435" fill="none" stroke="#333" stroke-width="2"/><text x="8" y="25">Price</text><text x="355" y="342">Quantity</text><path d="M85 55L385 275" fill="none" stroke="#195ca8" stroke-width="3"/><text x="387" y="280" fill="#195ca8">D₀</text><path d="M85 275L385 55" fill="none" stroke="#a43826" stroke-width="3"/><text x="387" y="54" fill="#a43826">S₀</text><circle cx="235" cy="165" r="5" fill="#333"/><text x="240" y="158">E₀</text>${reveal&&dl?`<path d="M${85+dl} 55L${385+dl} 275" fill="none" stroke="#195ca8" stroke-width="3" stroke-dasharray="8 5"/><text x="${355+dl}" y="299" fill="#195ca8">D₁</text>`:''}${reveal&&sl?`<path d="M${85+sl} 275L${385+sl} 55" fill="none" stroke="#a43826" stroke-width="3" stroke-dasharray="8 5"/><text x="${365+sl}" y="38" fill="#a43826">S₁</text>`:''}${reveal&&(dl||sl)?`<circle cx="${235+(dl+sl)/2}" cy="${165+(dl-sl)*11/30}" r="5" fill="#333"/><text x="${240+(dl+sl)/2}" y="${154+(dl-sl)*11/30}">E₁</text>`:''}${reveal&&(moveD||moveS)?`<circle cx="305" cy="${moveD?216:114}" r="7" fill="${moveD?'#195ca8':'#a43826'}"/><text x="285" y="${moveD?240:98}">New point</text>`:''}</svg>`}
function curve(){const c=curves[curveIndex];app.innerHTML=`<h2>Curve challenge · ${curveIndex+1}/${curves.length}</h2><p class="note">${esc(c.q)}</p><div id="graph">${graph(c,false)}</div><p class="muted">Illustrative graph. Solid lines are the original curves; dashed lines show shifts after checking. Equal-size shifts illustrate one possible outcome, not a known price result.</p><form id="curve-form"><label class="field"><span>1. What changes?</span><select id="shift" required><option value="">Choose</option>${options(['Demand left','Demand right','Supply left','Supply right','Movement along demand','Movement along supply','Both left','Both right'])}</select></label><div class="grid"><label class="field"><span>2. Equilibrium price</span><select id="price" required><option value="">Choose</option>${options(['Rises','Falls','Cannot determine','Not a new equilibrium'])}</select></label><label class="field"><span>3. Quantity</span><select id="quantity" required><option value="">Choose</option>${options(['Rises','Falls','Cannot determine','Quantity demanded rises','Quantity supplied rises'])}</select></label></div><button class="primary">Check reasoning</button></form><p id="curve-feedback" class="feedback" hidden aria-live="polite"></p><div class="tools"><button id="prev" ${curveIndex===0?'disabled':''}>Previous</button><button id="next">${curveIndex===curves.length-1?'Start again':'Next scenario'}</button></div>`;document.getElementById('curve-form').onsubmit=e=>{e.preventDefault();const vals=[document.getElementById('shift').value,document.getElementById('price').value,document.getElementById('quantity').value],want=[c.change,c.p,c.qty];let marks=vals.filter((v,i)=>v===want[i]).length;let f=document.getElementById('curve-feedback');f.hidden=false;f.className='feedback '+(marks===3?'correct':'incorrect');f.textContent=`${marks}/3. Change: ${c.change}. Price: ${c.p}. Quantity: ${c.qty}. ${c.why}`;document.getElementById('graph').innerHTML=graph(c,true);if(c.id)remember(c.id,marks===3)};document.getElementById('prev').onclick=()=>{curveIndex=Math.max(0,curveIndex-1);curve()};document.getElementById('next').onclick=()=>{curveIndex=(curveIndex+1)%curves.length;curve()};}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>change(b.dataset.mode));const initial=new URLSearchParams(location.search).get('mode');change(['learn','practice','curve','test','mistakes'].includes(initial)?initial:'learn');
})();
