const questions = [
{type:'output',topic:'Integer division',title:'What exactly is printed?',code:'System.out.println(17 / 5);',answer:'3',why:'Both operands are integers. Java discards the fractional part: 17 / 5 is 3.'},
{type:'output',topic:'Decimal division',title:'What exactly is printed?',code:'System.out.println(17.0 / 5);',answer:'3.4',why:'17.0 is a double literal, so this is floating-point division. The result is 3.4.'},
{type:'output',topic:'Remainder',title:'What exactly is printed?',code:'System.out.println(23 % 6);',answer:'5',why:'23 = 6 × 3 + 5, so the remainder is 5.'},
{type:'output',topic:'Order of operations',title:'Trace the expression, then write the output.',code:'System.out.println(2 + (9 - 3) * 4 / 3);',answer:'10',why:'The brackets give 6. Multiplication and division have equal priority and go left to right: 6 × 4 / 3 = 8. Then 2 + 8 = 10.'},
{type:'output',topic:'Concatenation',title:'Write the output on three separate lines.',code:'System.out.println("8" + 2 + 5);\nSystem.out.println(2 + 5 + "8");\nSystem.out.println("8" + (2 + 5));',answer:'825\n78\n87',why:'On line 1, + joins strings from the start. On line 2, 2 + 5 is calculated first. On line 3, the brackets force 2 + 5 to be calculated first.'},
{type:'mc',topic:'Concatenation',title:'Maya wants to print a total. Which replacement fixes her line?',code:'System.out.println("Total: " + 6 + 4);',actual:'Total: 64',target:'Total: 10',options:['System.out.println("Total: " + (6 + 4));','System.out.println("Total: " + "6 + 4");','System.out.println("Total: " + 6 * 4);','System.out.println(("Total: " + 6) + 4);'],answer:0,why:'Put the numeric addition in brackets. Without them, Java joins "Total: " to 6 and then to 4.'},
{type:'mc',topic:'Decimal division',title:'Noah wants a decimal answer. Which replacement fixes his calculation?',code:'System.out.println(9 / 2);',actual:'4',target:'4.5',options:['System.out.println(9 / 2 + 0.0);','System.out.println(9.0 / 2);','System.out.println((9 / 2) * 1.0);','System.out.println(9 % 2);'],answer:1,why:'Make at least one operand a decimal before the division. Adding 0.0 or multiplying by 1.0 afterward cannot recover the discarded fraction.'},
{type:'output',topic:'Variable updates',title:'Follow a through every statement. Write all four output lines.',code:'int a = 6;\nSystem.out.println(a += 3);\na++;\nSystem.out.println(a);\nSystem.out.println(a++);\nSystem.out.println(a);',answer:'9\n10\n10\n11',why:'a += 3 changes a to 9. The standalone a++ changes it to 10. Printing a++ uses 10 as the expression value and increments a to 11 before the next statement.'},
{type:'output',topic:'Variable updates',title:'Write both output lines.',code:'int points = 12;\npoints -= 4;\npoints--;\nSystem.out.println(points);\nSystem.out.println(points + 2);',answer:'7\n9',why:'points becomes 8, then 7. points + 2 evaluates to 9 but does not assign anything back to points.'},
{type:'mc',topic:'Remainder',title:'Ava packs 29 cards into groups of 6. She wants the number left over. Choose the fix.',code:'System.out.println(29 / 6);',actual:'4',target:'5',options:['System.out.println(29 - 6);','System.out.println(29.0 / 6);','System.out.println(29 % 6);','System.out.println(29 + 6);'],answer:2,why:'The / operator counts complete groups here. The % operator gives the leftover cards.'},
{type:'mc',topic:'Order of operations',title:'Leo wants the average of two scores. Which line is correct?',code:'System.out.println(7 + 8 / 2);',actual:'11',target:'7.5',options:['System.out.println((7 + 8) / 2);','System.out.println(7 + 8 / 2.0);','System.out.println((7 + 8) / 2.0);','System.out.println((7 + 8) % 2);'],answer:2,why:'Add the scores first, then divide using a decimal operand. (7 + 8) / 2 still uses integer division and gives 7.'},
{type:'output',topic:'Concatenation',title:'Watch the spaces. What exactly is printed?',code:'System.out.println("Java" + "Lab" + " " + 1 + 3);',answer:'JavaLab 13',why:'Concatenation adds no spaces of its own. Only the explicit " " adds a space. The final 1 and 3 are joined to the string, not added.'},
{type:'mc',topic:'Variable updates',title:'Which statement increases the current value of a by 3?',code:'int a = 8;\n// Insert one statement here.',options:['a = 3;','a + 3;','a += 3;','a++;'],answer:2,why:'a += 3 changes a from 8 to 11. a + 3; is not a valid standalone Java statement. a = 3 replaces the value, and a++ adds only 1.'},
{type:'output',topic:'Order of operations',title:'Write both output lines.',code:'System.out.println(20 / 3 * 3);\nSystem.out.println(20 / (3 * 3));',answer:'18\n2',why:'The first line evaluates left to right: 20 / 3 = 6, then 6 × 3 = 18. The second divides 20 by 9 using integer division, giving 2.'},
{type:'output',topic:'Variable updates',title:'Trace the variable and the printed text separately.',code:'int n = 4;\nSystem.out.println("n=" + n++);\nn += 2;\nSystem.out.println("n=" + n);',answer:'n=4\nn=7',why:'n++ contributes the old value 4 to the first string, then increments n to 5. Adding 2 changes n to 7.'},
{type:'mc',topic:'Integer division',title:'Which explanation of this result is correct?',code:'System.out.println(11 / 4);',actual:'2',options:['Java rounds every division result to the nearest integer.','Both operands are integers, so the fractional part is discarded.','println cannot display decimal numbers.','The / operator returns the remainder.'],answer:1,why:'Integer division truncates the fractional part. It does not round to the nearest integer. Decimal operands allow a decimal result.'},
{type:'free',topic:'Concatenation',title:'Repair the program: the sum is wrong.',prompt:'Sam wants the line below to display the sum of x and y. Replace only the println statement, keep both variables, and explain the bug.',code:'int x = 12;\nint y = 8;\nSystem.out.println("Sum: " + x + y);',actual:'Sum: 128',target:'Sum: 20',solution:'System.out.println("Sum: " + (x + y));',why:'The original line joins the label to x and then y. Brackets make Java add x and y before concatenation.',rubric:['My replacement uses both x and y and produces exactly Sum: 20.','My explanation describes concatenation and why brackets fix it.']},
{type:'free',topic:'Variable updates',title:'Repair the program: the updated score appears too late.',prompt:'Keep score initialized to 9. Rewrite the statements after its declaration so the score increases once and BOTH printed values are 10. Use only operators from the lesson.',code:'int score = 9;\nSystem.out.println(score++);\nSystem.out.println(score);',actual:'9 → 10 (two lines)',target:'10 → 10 (two lines)',solution:'score++;\nSystem.out.println(score);\nSystem.out.println(score);',why:'The expression score++ uses the old value and then increments the variable. Put the increment on its own line before either print. score += 1; or score = score + 1; would also work.',rubric:['My code increases score exactly once before both print statements.','I explain that score++ contributes the old value when used inside println.']},
{type:'free',topic:'Decimal division',title:'Repair the program: two mistakes in one average.',prompt:'Replace only the println statement, keep both variables, and explain both problems.',code:'int first = 8;\nint second = 9;\nSystem.out.println("Average: " + (first + second / 2));',actual:'Average: 12',target:'Average: 8.5',solution:'System.out.println("Average: " + ((first + second) / 2.0));',why:'In the original, second / 2 is calculated first and uses integer division (9 / 2 = 4). Add the scores before dividing, and use a decimal operand for the division.',rubric:['My code adds first and second before dividing, and produces Average: 8.5.','I explain both operation order and the need for decimal division.']},
{type:'free',topic:'Remainder',title:'Write a short program: convert seconds.',prompt:'Use totalSeconds to calculate complete minutes and leftover seconds. Write the statements after the declaration. Do not hard-code 2 or 5 as the answers. Briefly explain your two calculations.',code:'int totalSeconds = 125;\n// Your statements go here.',target:'Minutes: 2\nSeconds: 5',solution:'System.out.println("Minutes: " + totalSeconds / 60);\nSystem.out.println("Seconds: " + totalSeconds % 60);',why:'Integer division by 60 gives the complete minutes; the remainder modulo 60 gives the seconds left over. Extra brackets and intermediate int variables are also valid.',rubric:['My code uses totalSeconds / 60 and totalSeconds % 60 (or equivalent calculations) and prints the requested lines.','I explain why the quotient gives minutes and the remainder gives seconds.']}
];
let current=0,submitted=false;const answers=questions.map(()=>''),notes=questions.map(()=>''),checks=questions.map(()=>[false,false]);
const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>String(s).replace(/\r/g,'').split('\n').map(l=>l.trim()).join('\n').trim();
function correct(i){return questions[i].type==='mc'?answers[i]===questions[i].answer:normalize(answers[i])===questions[i].answer}
function answered(i){return typeof answers[i]==='number'||String(answers[i]).trim().length>0}
function updateNav(){ $('navigator').innerHTML=questions.map((q,i)=>`<button aria-label="Question ${i+1}${answered(i)?', answered':''}" ${i===current?'aria-current="step"':''} class="${i===current?'active ':''}${answered(i)?'answered ':''}${submitted&&q.type!=='free'?(correct(i)?'correct':'incorrect'):''}" data-index="${i}">${i+1}</button>`).join('');$('navigator').querySelectorAll('button').forEach(b=>b.onclick=()=>{current=+b.dataset.index;render()});const count=answers.filter((_,i)=>answered(i)).length;$('progress').textContent=`${count} of 20 answered`;$('bar').style.width=`${count/20*100}%`}
function render(){const q=questions[current];$('question').innerHTML=`<span class="tag">QUESTION ${String(current+1).padStart(2,'0')} / ${q.type==='free'?'CODE REPAIR · SELF-REVIEW':q.type==='mc'?'SELECT ONE · 1 POINT':'PREDICT OUTPUT · 1 POINT'}</span><h2>${esc(q.title)}</h2>${q.prompt?`<p>${esc(q.prompt)}</p>`:''}<pre><code>${esc(q.code)}</code></pre>${q.actual||q.target?`<div class="console">${q.actual?`<p><small>CURRENT OUTPUT</small><code>${esc(q.actual)}</code></p>`:''}${q.target?`<p><small>EXPECTED OUTPUT</small><code style="white-space:pre-wrap">${esc(q.target)}</code></p>`:''}</div>`:''}${q.type==='mc'?`<fieldset style="border:0;padding:0;margin:0"><legend class="field">Choose one answer</legend><div class="options">${q.options.map((o,i)=>`<label class="option"><input type="radio" name="choice" value="${i}" ${answers[current]===i?'checked':''} ${submitted?'disabled':''}><code>${esc(o)}</code></label>`).join('')}</div></fieldset>`:`<label class="field" for="answer">${q.type==='free'?'Your corrected code':'Your output'}</label><textarea id="answer" spellcheck="false" ${submitted?'readonly':''} placeholder="${q.type==='free'?'Write your Java statements here…':'Type the exact output; put each output line on a new line.'}">${esc(answers[current])}</textarea>${q.type==='free'?`<label class="field" for="reason">Explain your reasoning</label><textarea id="reason" spellcheck="true" ${submitted?'readonly':''}>${esc(notes[current])}</textarea>`:''}`}${submitted?feedback(q):''}`;
if(!submitted){if(q.type==='mc')$('question').querySelectorAll('input').forEach(el=>el.onchange=()=>{answers[current]=+el.value;updateNav()});else{$('answer').oninput=e=>{answers[current]=e.target.value;updateNav()};if(q.type==='free')$('reason').oninput=e=>notes[current]=e.target.value}}
$('question').querySelectorAll('[data-check]').forEach(el=>el.onchange=()=>{checks[current][+el.dataset.check]=el.checked;renderSummary()});$('prev').disabled=current===0;$('next').disabled=current===19;$('position').textContent=`${current+1} / 20`;updateNav();}
function feedback(q){return `<div class="feedback"><strong class="${q.type==='free'?'':correct(current)?'good':'bad'}">${q.type==='free'?'Compare your solution':correct(current)?'Correct':'Review this question'}</strong><p>${q.type==='free'?'One valid solution:':'Expected answer:'}</p><pre><code>${esc(q.type==='mc'?q.options[q.answer]:q.type==='free'?q.solution:q.answer)}</code></pre><p>${esc(q.why)}</p>${q.type==='free'?`<p class="small">This code is not executed or automatically graded. Equivalent working solutions are valid. Check each criterion you met (1 point each):</p>${q.rubric.map((r,i)=>`<label class="selfmark"><input type="checkbox" data-check="${i}" ${checks[current][i]?'checked':''}> ${esc(r)}</label>`).join('')}`:''}</div>`}
function renderSummary(){let score=0;const weak={};questions.forEach((q,i)=>{if(q.type!=='free'){if(correct(i))score++;else weak[q.topic]=(weak[q.topic]||0)+1}});const self=checks.flat().filter(Boolean).length;$('summary').hidden=false;$('summary').innerHTML=`<span class="tag">EXAM REVIEW</span><h2>${score} / 16 <span class="small">auto-marked</span></h2><p>Code tasks: <strong>${self} / 8</strong> self-assessed points. Review questions 17–20 and tick the criteria you met. This is separate from your automatic score.</p>${Object.keys(weak).length?`<p><strong>Focus your review on:</strong></p><ul>${Object.entries(weak).map(([t,n])=>`<li>${esc(t)} — ${n} question${n>1?'s':''} to revisit</li>`).join('')}</ul>`:'<p class="good">All automatic questions correct. Now check your written solutions and explanations.</p>'}<p class="small">Use the numbered buttons to compare every answer with its explanation. Unanswered automatic questions receive 0 points.</p><button id="retry">Start a fresh attempt</button>`;$('retry').onclick=()=>{if(confirm('Clear all answers and start again?')){answers.fill('');notes.fill('');checks.forEach(c=>c.fill(false));submitted=false;current=0;$('summary').hidden=true;$('submit').textContent='Submit exam';render();window.scrollTo({top:0,behavior:'smooth'})}}}
$('prev').onclick=()=>{if(current>0){current--;render()}};$('next').onclick=()=>{if(current<19){current++;render()}};$('submit').onclick=()=>{if(submitted){$('summary').scrollIntoView({behavior:'smooth'});$('summary').focus();return}const remaining=answers.filter((_,i)=>!answered(i)).length;if(!confirm(remaining?`${remaining} question(s) are unanswered. Submit and reveal all solutions?`:'Submit your exam and reveal all solutions?'))return;submitted=true;renderSummary();render();$('submit').textContent='View results';$('summary').scrollIntoView({behavior:'smooth'});$('summary').focus()};render();
