const lesson14 = [
{type:'mc',topic:'Syntax errors',title:'Why will this line not compile?',code:'int age = 15',options:['A semicolon is missing.','15 must be a double.','age must start with a capital letter.','The variable must be printed.'],answer:0,why:'A declaration statement must end with a semicolon.'},
{type:'mc',topic:'Syntax errors',title:'Only age has been declared. Choose the repair.',code:'int age = 15;\nage = Age + 1;',options:['age = "Age" + 1;','age = age + 1;','Age = age + 1;','age + 1;'],answer:1,why:'Java names are case-sensitive. Age is not the declared variable age.'},
{type:'mc',topic:'Syntax errors',title:'Which line prints the message correctly?',code:'int age = 15;',options:['System.out.print(My age is + age);','System.out.print("My age is " + age);','System.out.print("My age is " age);','System.out.print("My age is + age);'],answer:1,why:'The text needs matching quotes, and + joins it to the variable value.'},
{type:'mc',topic:'Syntax errors',title:'Repair the unmatched parenthesis.',code:'System.out.print("Goodbye";',options:['System.out.print("Goodbye");','System.out.print("Goodbye"));','System.out.print(Goodbye);','System.out.print("Goodbye");)'],answer:0,why:'Close the method call before its semicolon.'},
{type:'mc',topic:'Logic errors',title:'The intended average is 7.5. Classify the mistake.',code:'System.out.println((7 + 8) / 2);',options:['Syntax error: the compiler rejects it.','Logic error: it runs but gives the wrong answer.','Runtime error: it crashes.','Style issue only.'],answer:1,why:'This compiles and prints 7. Integer division gives the wrong result for the intended decimal average.'},
{type:'mc',topic:'Runtime errors',title:'What happens when this division executes?',code:'int divisor = 0;\nSystem.out.println(10 / divisor);',options:['It prints 0.','It prints Infinity.','It throws ArithmeticException at runtime.','It cannot compile because divisor is a variable.'],answer:2,why:'Integer division by zero throws ArithmeticException at runtime.'},
{type:'mc',topic:'Debugging',title:'A program compiles. What does that establish?',code:'// The compiler reports no errors.',options:['Every calculation is correct.','All requirements are met.','The program cannot crash.','Compilation succeeded, but behavior still needs testing.'],answer:3,why:'Compilation does not prove correct logic or rule out runtime failures.'},
{type:'mc',topic:'Debugging',title:'Which test exposes the average calculation bug?',code:'int first = 7;\nint second = 8;\ndouble average = (first + second) / 2;',options:['Only check that it compiles.','Compare average with the expected value 7.5.','Rename average.','Add a comment saying it works.'],answer:1,why:'The actual value is 7.0. Assigning integer division to a double does not recover the discarded fraction.'},
{type:'mc',topic:'Naming',title:'Choose the clearest course-style name.',code:'// Store the number of students in a class.',options:['x','ns','numberOfStudents','Numberofstudents'],answer:2,why:'This is descriptive English and uses lower camel case.'},
{type:'mc',topic:'Naming',title:'Choose the best constant declaration.',code:'// A fixed tax rate of 13 percent.',options:['final double TAX_RATE = 0.13;','final double taxrate = 0.13;','double TAX_RATE = 13;','final double TaxRate = 0.13;'],answer:0,why:'A constant uses final and an uppercase name. 0.13 represents 13 percent.'},
{type:'mc',topic:'Naming',title:'Which class / method pair follows the conventions?',code:'// Name a class and a method for a checkout program.',options:['cashier / CalculateTotal','Cashier / calculateTotal','CASHIER / CALCULATETOTAL','cashier / calculate_total'],answer:1,why:'Class names start uppercase; method names start lowercase and use mixed case.'},
{type:'mc',topic:'Comments',title:'Which comment best explains this section?',code:'double tax = subtotal * TAX_RATE;\ndouble total = subtotal + tax;',options:['// Multiply, then add.','// Set tax, then set total.','// Calculate sales tax and the amount the customer owes.','// This code is perfect.'],answer:2,why:'A useful comment explains the purpose of a logical section.'},
{type:'mc',topic:'Whitespace',title:'Which layout matches the style guide?',code:'// Read input, calculate a total, then print a receipt.',options:['Put all statements on one line.','Double-space every line of code.','Group related statements, separate sections with blank lines, and indent blocks.','Indent only after fixing all bugs.'],answer:2,why:'Logical paragraphs and indentation make structure visible while you write and debug.'},
{type:'mc',topic:'Style',title:'Which change improves style while preserving output?',code:'int a=12;\nSystem.out.println(a);',options:['Change 12 to 13.','Remove the semicolon.','Rename a consistently to numberOfTickets and space the assignment.','Change println to print.'],answer:2,why:'A descriptive rename and spacing preserve the value and output.'},
{type:'mc',topic:'Logic errors',title:'Which repair calculates the rectangle perimeter?',code:'int width = 8;\nint height = 3;\nint perimeter = width + height * 2;',options:['int perimeter = width * height;','int perimeter = (width + height) * 2;','int perimeter = width + height;','int perimeter = width + height / 2;'],answer:1,why:'The perimeter is twice the sum of the dimensions: 22. The original calculates 14.'},
{type:'mc',topic:'Debugging',title:'After repairing a logic error, what comes next?',code:'// The calculation has been changed.',options:['Retest the failing example and other representative inputs against expected results.','Stop because edited code is always correct.','Only reformat the source.','Remove all comments.'],answer:0,why:'Retesting checks the repair; other cases can reveal remaining incorrect assumptions.'},
{type:'free',topic:'Syntax errors',title:'Repair three compile-time mistakes.',prompt:'Rewrite the snippet and explain each correction. The intended output is My age is 16.',code:'int age = 15\nage = Age + 1;\nSystem.out.println("My age is " + age;',solution:'int age = 15;\nage = age + 1;\nSystem.out.println("My age is " + age);',why:'Add a semicolon, use lowercase age, and close the println parenthesis.',rubric:['My code compiles and prints My age is 16.','I explain all three corrections, including case sensitivity.']},
{type:'free',topic:'Logic errors',title:'Repair and test the rectangle calculation.',prompt:'Replace the calculation. Explain the error and provide a second test with an expected result.',code:'int width = 8;\nint height = 3;\nint perimeter = width + height * 2;\nSystem.out.println(perimeter);',target:'22',solution:'int perimeter = (width + height) * 2;',why:'The original doubles only height because multiplication happens first. Another test: width 5 and height 4 should give 18.',rubric:['I double the sum and explain the precedence error.','I give another input pair and its correct expected perimeter.']},
{type:'free',topic:'Style',title:'Rewrite for clarity.',prompt:'Preserve the calculation. Use descriptive names, a named constant, indentation and a useful comment. Keep the class name Receipt.',code:'public class Receipt{\npublic static void main(String[] args){\ndouble x=20;double y=x*0.13;System.out.println(x+y);\n}\n}',solution:'public class Receipt {\n    public static void main(String[] args) {\n        final double TAX_RATE = 0.13;\n        double subtotal = 20;\n\n        // Calculate tax and print the amount owed.\n        double tax = subtotal * TAX_RATE;\n        System.out.println(subtotal + tax);\n    }\n}',why:'Meaningful names expose purpose. Indentation shows nesting; blank lines separate logical sections.',rubric:['I preserve the calculation and use descriptive variables plus an uppercase final constant.','I use consistent indentation, logical spacing and a purpose-focused comment.']},
{type:'free',topic:'Debugging',title:'Repair and classify both failures.',prompt:'A should print 7.5. B should print 5 using a divisor of 2. Rewrite both and explain how the original failures differ. Treat A and B as independent snippets.',code:'// A\nSystem.out.println((7 + 8) / 2);\n\n// B\nint divisor = 0;\nSystem.out.println(10 / divisor);',solution:'// A\nSystem.out.println((7 + 8) / 2.0);\n\n// B\nint divisor = 2;\nSystem.out.println(10 / divisor);',why:'A runs but prints the wrong result: a logic error. B throws an exception at runtime. Neither needs a syntax repair.',rubric:['My repairs produce 7.5 for A and 5 for B.','I distinguish a wrong result from a runtime exception.']}
];
const formattingQuestions = [
{type:'output',topic:'Precision',title:'What exactly is printed?',prompt:'Assume a locale that uses a decimal point.',code:'System.out.printf("%.2f", 12.346);',answer:'12.35',why:'%.2f rounds to two decimal places.'},
{type:'output',topic:'Padding',title:'What exactly is printed?',code:'System.out.printf("%04d", 7);',answer:'0007',why:'The minimum width is four characters; the 0 flag pads with zeros.'},
{type:'mc',topic:'Format specifiers',title:'Choose the matching format string.',code:'// Arguments in order: "Java", 3, 2.5',options:['"%d %s %.1f"','"%s %d %.1f"','"%s %f %d"','"%d %d %d"'],answer:1,why:'%s formats the string, %d the integer, and %.1f the decimal with one decimal place.'},
{type:'mc',topic:'String.format',title:'What does this statement do?',code:'String label = String.format("%03d", 7);',options:['Prints 007 immediately.','Assigns the returned string "007" to label.','Changes 7 to 700.','Fails because no println follows.'],answer:1,why:'String.format returns a string; it does not print it.'}
];
