import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";

const repoRoot = process.cwd();
const studyPilotRoot = path.join(repoRoot, "studypilot");
const dataRoot = path.join(studyPilotRoot, "data");
const outputDir = path.join(studyPilotRoot, "d1", "generated");
const outputFile = path.join(outputDir, "import-current-data.sql");

const SECTION_TITLES = {
  keyConcepts: "Key concepts",
  teacherNotes: "Teacher notes summary",
  resources: "Useful learning resources",
  quizEasy: "Easy quiz questions",
  quizMedium: "Medium quiz questions",
  quizHard: "Hard quiz questions",
  feynmanChecklist: "Feynman mastery checklist",
  applications: "Real-world applications",
  formulas: "Formulas",
  solvingSteps: "Step-by-step solving process",
  examples: "Worked examples",
  commonMistakes: "Common mistakes",
  practiceEasy: "Easy practice questions",
  practiceMedium: "Medium practice questions",
  practiceHard: "Hard practice questions",
  readingFocus: "Reading focus",
  writingTips: "Writing structure support",
  structureTemplates: "Structure templates",
  vocabulary: "Vocabulary support",
  practicePrompts: "Short practice prompts",
  beforeClass: "Before class",
  keywords: "Keywords",
  quickQuestions: "Quick questions",
  labSteps: "Lab steps",
  propertyUseLinks: "Property to use ideas",
  teacherQuestions: "Teacher questions",
  flexibleThinkingExamples: "Flexible thinking"
};

const statements = [];

await fs.mkdir(outputDir, { recursive: true });

const [
  scienceData,
  mathData,
  englishData,
  todayData,
  weekData,
  nextWeekData,
  mistakesData,
  classroomData,
  uploadAnalysis
] = await Promise.all([
  readJson(path.join(dataRoot, "science.json")),
  readJson(path.join(dataRoot, "math.json")),
  readJson(path.join(dataRoot, "english.json")),
  readJson(path.join(dataRoot, "today.json")),
  readJson(path.join(dataRoot, "week.json")),
  readJson(path.join(dataRoot, "next-week.json")),
  readJson(path.join(dataRoot, "mistakes.json")),
  readJson(path.join(dataRoot, "classroom-updates.json")),
  readJson(path.join(dataRoot, "upload-analysis.json"))
]);

writeHeader();
clearTables();
seedUploads(uploadAnalysis);
seedScienceSchedule(scienceData.schedule);
seedUpcomingSupport("science", scienceData.upcomingSupport || []);
seedSubjectCards("science", scienceData.topics || [], scienceTopicSections());
seedSubjectCards("math", mathData.topics || [], mathTopicSections());
seedSubjectCards("english", englishData.topics || [], englishTopicSections());
seedTasks("today", todayData.tasks || []);
seedTasks("week", weekData.tasks || []);
seedTasks("nextWeek", nextWeekData.tasks || []);
seedMistakes(mistakesData.mistakes || []);
seedClassroomSync(classroomData);

await fs.writeFile(outputFile, `${statements.join("\n")}\n`, "utf8");

console.log(`Wrote D1 import SQL to ${outputFile}`);

function writeHeader() {
  statements.push("-- Generated by studypilot/scripts/export_studypilot_json_to_d1.mjs");
  statements.push("-- Import this file after running the D1 schema migrations.");
  statements.push("PRAGMA foreign_keys = ON;");
  statements.push("");
  statements.push("-- Ensure core subject rows exist before importing dependent records.");
  statements.push("INSERT OR IGNORE INTO subjects (id, slug, name) VALUES ('subject-science', 'science', 'Science');");
  statements.push("INSERT OR IGNORE INTO subjects (id, slug, name) VALUES ('subject-math', 'math', 'Math');");
  statements.push("INSERT OR IGNORE INTO subjects (id, slug, name) VALUES ('subject-english', 'english', 'English');");
}

function clearTables() {
  const tableOrder = [
    "classroom_items",
    "classroom_topics",
    "classroom_courses",
    "classroom_sync_runs",
    "mistakes",
    "study_tasks",
    "science_schedule_key_dates",
    "science_schedule_units",
    "science_schedule",
    "upcoming_support_sections",
    "upcoming_support_items",
    "subject_topic_sections",
    "subject_topic_cards",
    "uploads"
  ];

  for (const tableName of tableOrder) {
    statements.push(`DELETE FROM ${tableName};`);
  }
}

function seedUploads(uploadAnalysis) {
  const items = Array.isArray(uploadAnalysis?.items) ? uploadAnalysis.items : [];
  for (const item of items) {
    const id = stableId("upload", item.relativePath);
    insert("uploads", {
      id,
      source_mode: "local",
      category: normalizeUploadCategory(item.category),
      original_name: item.fileName || item.relativePath,
      storage_path: item.relativePath || null,
      mime_type: item.mimeType || null,
      size_bytes: item.sizeBytes ?? null,
      uploaded_at: item.modifiedAt || uploadAnalysis.generatedAt || nowIso(),
      notes: item.summary || null
    });
  }
}

function seedScienceSchedule(schedule) {
  if (!schedule) {
    return;
  }

  const scheduleId = "science-schedule-main";
  insert("science_schedule", {
    id: scheduleId,
    title: schedule.title || "Science Schedule",
    overview: schedule.overview || "",
    current_exam_subject: schedule.currentExamRange?.subject || null,
    current_exam_range_start: schedule.currentExamRange?.rangeStart || null,
    current_exam_note: schedule.currentExamRange?.note || null,
    updated_at: nowIso()
  });

  for (const [index, unit] of (schedule.units || []).entries()) {
    insert("science_schedule_units", {
      id: stableId("science-unit", `${index}-${unit.name}`),
      schedule_id: scheduleId,
      unit_order: index,
      name: unit.name || `Unit ${index + 1}`,
      window_label: unit.window || "",
      focus: unit.focus || null,
      notes: unit.notes || null
    });
  }

  for (const [index, item] of (schedule.keyDates || []).entries()) {
    insert("science_schedule_key_dates", {
      id: stableId("science-key-date", `${index}-${item.date}-${item.label}`),
      schedule_id: scheduleId,
      date_order: index,
      date_label: item.date || "",
      label: item.label || "",
      note: item.note || null
    });
  }
}

function seedUpcomingSupport(subjectSlug, items) {
  for (const [index, item] of items.entries()) {
    const supportId = stableId("upcoming-support", `${subjectSlug}-${index}-${item.topic}`);
    insert("upcoming_support_items", {
      id: supportId,
      subject_slug: subjectSlug,
      when_label: item.when || null,
      topic: item.topic || `Support ${index + 1}`,
      support_type: item.type || null,
      summary: item.summary || "",
      source_kind: "manual",
      source_upload_id: null,
      created_at: nowIso(),
      updated_at: nowIso()
    });

    const keys = [
      "beforeClass",
      "keywords",
      "quickQuestions",
      "resources",
      "labSteps",
      "propertyUseLinks",
      "teacherQuestions",
      "flexibleThinkingExamples"
    ];

    for (const key of keys) {
      seedSectionItems("upcoming_support_sections", supportId, key, item[key] || []);
    }
  }
}

function seedSubjectCards(subjectSlug, cards, sectionKeys) {
  for (const [index, card] of cards.entries()) {
    const cardId = stableId("subject-card", `${subjectSlug}-${index}-${card.topic}`);
    insert("subject_topic_cards", {
      id: cardId,
      subject_slug: subjectSlug,
      title: card.topic || `Card ${index + 1}`,
      summary: card.summary || "",
      source_kind: "manual",
      source_upload_id: inferUploadId(card),
      source_ref: null,
      created_at: nowIso(),
      updated_at: nowIso()
    });

    for (const key of sectionKeys) {
      seedSectionItems("subject_topic_sections", cardId, key, card[key] || []);
    }
  }
}

function seedSectionItems(tableName, parentId, sectionKey, items) {
  const values = Array.isArray(items) ? items : [];
  const sectionTitle = SECTION_TITLES[sectionKey] || sectionKey;

  values.forEach((item, index) => {
    const common = {
      id: stableId(`${tableName}-item`, `${parentId}-${sectionKey}-${index}-${serializeItem(item)}`),
      [tableName === "subject_topic_sections" ? "card_id" : "support_id"]: parentId,
      section_key: sectionKey,
      section_title: sectionTitle,
      item_order: index
    };

    if (item && typeof item === "object" && item.label) {
      insert(tableName, {
        ...common,
        item_type: "resource",
        text_value: null,
        label: item.label,
        url: item.url || null
      });
      return;
    }

    insert(tableName, {
      ...common,
      item_type: "text",
      text_value: String(item),
      label: null,
      url: null
    });
  });
}

function seedTasks(bucket, tasks) {
  for (const [index, task] of tasks.entries()) {
    const subjectSlug = normalizeSubjectSlug(task.subject);
    insert("study_tasks", {
      id: stableId("task", `${bucket}-${index}-${task.subject}-${task.topic}-${task.dueDate}`),
      bucket,
      subject_slug: subjectSlug,
      topic: task.topic || `Task ${index + 1}`,
      task_type: task.type || "task",
      note: task.note || "",
      due_date: task.dueDate || null,
      priority: normalizePriority(task.priority),
      resource_label: task.resourceLabel || null,
      resource_url: task.resourceLink || null,
      classroom_topic: task.classroomTopic || null,
      classroom_type: task.classroomType || null,
      source_kind: normalizeTaskSource(task.source),
      source_key: task.sourceKey || null,
      source_upload_id: inferUploadId(task),
      is_active: 1,
      created_at: nowIso(),
      updated_at: nowIso()
    });
  }
}

function seedMistakes(mistakes) {
  for (const [index, mistake] of mistakes.entries()) {
    insert("mistakes", {
      id: stableId("mistake", `${index}-${mistake.subject}-${mistake.topic}-${mistake.date}`),
      subject_slug: normalizeSubjectSlug(mistake.subject),
      topic: mistake.topic || "",
      subtopic: mistake.subtopic || null,
      mistake_date: mistake.date || null,
      error_type: mistake.errorType || "",
      question: mistake.question || "",
      student_answer: mistake.studentAnswer || "",
      correct_answer: mistake.correctAnswer || "",
      explanation: mistake.explanation || "",
      correction: mistake.correction || "",
      retry_status: mistake.retryStatus || "",
      mastery_level: Number.isFinite(Number(mistake.masteryLevel)) ? Number(mistake.masteryLevel) : 1,
      source_kind: normalizeMistakeSource(mistake.source),
      source_upload_id: inferUploadId(mistake),
      image_path: mistake.imagePath || null,
      created_at: nowIso(),
      updated_at: nowIso()
    });
  }
}

function seedClassroomSync(classroomData) {
  if (!classroomData || !Array.isArray(classroomData.classrooms)) {
    return;
  }

  const runId = stableId("classroom-run", classroomData.generatedAt || nowIso());
  insert("classroom_sync_runs", {
    id: runId,
    generated_at: classroomData.generatedAt || nowIso(),
    account: classroomData.account || null,
    login_status: classroomData.loginStatus || null,
    profile_dir: classroomData.profileDir || null,
    notes_json: JSON.stringify(classroomData.notes || []),
    created_at: nowIso()
  });

  for (const course of classroomData.classrooms) {
    const courseId = stableId("classroom-course", `${runId}-${course.key}`);
    insert("classroom_courses", {
      id: courseId,
      run_id: runId,
      course_key: course.key || "unknown",
      name: course.name || course.key || "Classroom course",
      url: course.url || null,
      page_title: course.pageTitle || null,
      authenticated: course.authenticated ? 1 : 0
    });

    (course.topics || []).forEach((topicName, index) => {
      insert("classroom_topics", {
        id: stableId("classroom-topic", `${courseId}-${index}-${topicName}`),
        course_id: courseId,
        topic_name: topicName,
        topic_order: index
      });
    });

    (course.topicSections || []).forEach((section, sectionIndex) => {
      (section.items || []).forEach((item, itemIndex) => {
        const recentStrings = Array.isArray(course.recentItems) ? course.recentItems : [];
        const recentPrefix = `${section.topic}: ${item.title}`;
        insert("classroom_items", {
          id: stableId("classroom-item", `${courseId}-${sectionIndex}-${itemIndex}-${section.topic}-${item.title}`),
          course_id: courseId,
          topic_name: section.topic || "General",
          title: item.title || "",
          meta: item.meta || null,
          item_order: itemIndex,
          is_recent: recentStrings.some((entry) => String(entry).startsWith(recentPrefix)) ? 1 : 0,
          created_at: nowIso()
        });
      });
    });
  }
}

function scienceTopicSections() {
  return ["keyConcepts", "teacherNotes", "resources", "quizEasy", "quizMedium", "quizHard", "feynmanChecklist", "applications"];
}

function mathTopicSections() {
  return ["formulas", "solvingSteps", "examples", "commonMistakes", "practiceEasy", "practiceMedium", "practiceHard"];
}

function englishTopicSections() {
  return ["readingFocus", "writingTips", "structureTemplates", "vocabulary", "resources", "practicePrompts"];
}

function inferUploadId(item) {
  const candidates = [];

  if (typeof item?.resourceLink === "string") {
    candidates.push(item.resourceLink);
  }
  if (typeof item?.imagePath === "string") {
    candidates.push(item.imagePath);
  }
  if (Array.isArray(item?.resources)) {
    item.resources.forEach((entry) => {
      if (entry && typeof entry === "object" && typeof entry.url === "string") {
        candidates.push(entry.url);
      }
    });
  }

  const matched = candidates.find((value) => value.includes("uploads/"));
  if (!matched) {
    return null;
  }

  const normalizedPath = matched.replace(/^(\.\.\/)+/, "");
  return stableId("upload", normalizedPath);
}

function normalizeSubjectSlug(subject) {
  const normalized = String(subject || "").trim().toLowerCase();
  if (normalized === "science") {
    return "science";
  }
  if (normalized === "math") {
    return "math";
  }
  if (normalized === "english") {
    return "english";
  }
  return "science";
}

function normalizePriority(priority) {
  const normalized = String(priority || "").trim().toLowerCase();
  if (normalized === "high") {
    return "High";
  }
  if (normalized === "low") {
    return "Low";
  }
  return "Medium";
}

function normalizeTaskSource(source) {
  const normalized = String(source || "").trim().toLowerCase();
  if (normalized === "classroom-sync") {
    return "classroom_sync";
  }
  if (normalized === "codex-chat-upload") {
    return "chat_upload";
  }
  return "manual";
}

function normalizeMistakeSource(source) {
  const normalized = String(source || "").trim().toLowerCase();
  if (normalized === "codex-chat-upload") {
    return "chat_upload";
  }
  return "manual";
}

function normalizeUploadCategory(category) {
  const normalized = String(category || "").trim().toLowerCase();
  if (["docs", "mistakes", "timetable"].includes(normalized)) {
    return normalized;
  }
  return "other";
}

function insert(tableName, record) {
  const columns = Object.keys(record);
  const values = columns.map((column) => sqlValue(record[column]));
  statements.push(`INSERT INTO ${tableName} (${columns.join(", ")}) VALUES (${values.join(", ")});`);
}

function sqlValue(value) {
  if (value === null || value === undefined) {
    return "NULL";
  }
  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "NULL";
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

function stableId(prefix, input) {
  const digest = crypto.createHash("sha1").update(`${prefix}:${input}`).digest("hex").slice(0, 16);
  return `${prefix}-${digest}`;
}

function serializeItem(item) {
  if (item && typeof item === "object") {
    return JSON.stringify(item);
  }
  return String(item);
}

function nowIso() {
  return new Date().toISOString();
}

async function readJson(filePath) {
  const raw = await fs.readFile(filePath, "utf8");
  return JSON.parse(raw);
}
